# This is a minimal makefile only used for the examples. If you want a makefile
# for your project, take one from the templates inside examples/templates.

BINDIRS	:= data

include ../../Makefile.example.blocksds
