# SPDX-License-Identifier: CC0-1.0
#
# SPDX-FileContributor: Antonio Niño Díaz, 2023

.PHONY: all clean

MAKE	:= make

all:
	@for i in `ls`; do \
		if test -e $$i/Makefile.blocksds ; then \
			cd $$i; \
			$(MAKE) -f Makefile.blocksds --no-print-directory || { exit 1;}; \
			cd ..; \
		fi; \
	done;

clean:
	@for i in `ls`; do \
		if test -e $$i/Makefile.blocksds ; then \
			cd $$i; \
			$(MAKE) -f Makefile.blocksds clean --no-print-directory || { exit 1;}; \
			cd ..; \
		fi; \
	done;
